python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 deep2
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 deep3
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 3d-hst-v4.1.5
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 ages
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 mosdef-16aug2016
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 vipers-pdr2
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 gama-dr2
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 sdss-dr14
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 eboss-dr14
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 cosmos2015-v1.1
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 cosmos-acs
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 spies-stripe82
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 fmost-cosmos-v1.0
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 cfhtls
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 vvds
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 spies-dr1
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 shela
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 wigglez-dr1
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 6dfgs
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 2dfgrs
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 2mrs
python "/global/u2/r/rongpu/git/desi-truth-table/decals_matching.py" 5.0 gama-dr3
