python legacy_surveys_matching_dr9sv.py 9sv 2dfgrs --field north
python legacy_surveys_matching_dr9sv.py 9sv 2dflens --field north
python legacy_surveys_matching_dr9sv.py 9sv 2mrs --field north
python legacy_surveys_matching_dr9sv.py 9sv 3d-hst --field north
python legacy_surveys_matching_dr9sv.py 9sv 6dfgs --field north
python legacy_surveys_matching_dr9sv.py 9sv ages --field north
python legacy_surveys_matching_dr9sv.py 9sv cosmos2015-v1 --field north
python legacy_surveys_matching_dr9sv.py 9sv deep2 --field north
python legacy_surveys_matching_dr9sv.py 9sv deep3 --field north
python legacy_surveys_matching_dr9sv.py 9sv fmos-cosmos --field north
python legacy_surveys_matching_dr9sv.py 9sv gama-dr3 --field north
python legacy_surveys_matching_dr9sv.py 9sv mosdef-final --field north
python legacy_surveys_matching_dr9sv.py 9sv ozdes-dr1 --field north
python legacy_surveys_matching_dr9sv.py 9sv primus --field north
python legacy_surveys_matching_dr9sv.py 9sv s82mgc --field north
python legacy_surveys_matching_dr9sv.py 9sv sdss-dr16 --field north
python legacy_surveys_matching_dr9sv.py 9sv vipers-pdr2 --field north
python legacy_surveys_matching_dr9sv.py 9sv vvds --field north
python legacy_surveys_matching_dr9sv.py 9sv wigglez-final --field north
python legacy_surveys_matching_dr9sv.py 9sv cfhtls --field north
python legacy_surveys_matching_dr9sv.py 9sv cosmos-acs --field north
python legacy_surveys_matching_dr9sv.py 9sv hsc-dr2 --field north
python legacy_surveys_matching_dr9sv.py 9sv shela --field north
python legacy_surveys_matching_dr9sv.py 9sv spies-dr1 --field north

############################################################

python legacy_surveys_matching_dr9sv.py 9sv 2dfgrs --field south
python legacy_surveys_matching_dr9sv.py 9sv 2dflens --field south
python legacy_surveys_matching_dr9sv.py 9sv 2mrs --field south
python legacy_surveys_matching_dr9sv.py 9sv 3d-hst --field south
python legacy_surveys_matching_dr9sv.py 9sv 6dfgs --field south
python legacy_surveys_matching_dr9sv.py 9sv ages --field south
python legacy_surveys_matching_dr9sv.py 9sv cosmos2015-v1 --field south
python legacy_surveys_matching_dr9sv.py 9sv deep2 --field south
python legacy_surveys_matching_dr9sv.py 9sv deep3 --field south
python legacy_surveys_matching_dr9sv.py 9sv fmos-cosmos --field south
python legacy_surveys_matching_dr9sv.py 9sv gama-dr3 --field south
python legacy_surveys_matching_dr9sv.py 9sv mosdef-final --field south
python legacy_surveys_matching_dr9sv.py 9sv ozdes-dr1 --field south
python legacy_surveys_matching_dr9sv.py 9sv primus --field south
python legacy_surveys_matching_dr9sv.py 9sv s82mgc --field south
python legacy_surveys_matching_dr9sv.py 9sv sdss-dr16 --field south
python legacy_surveys_matching_dr9sv.py 9sv vipers-pdr2 --field south
python legacy_surveys_matching_dr9sv.py 9sv vvds --field south
python legacy_surveys_matching_dr9sv.py 9sv wigglez-final --field south
python legacy_surveys_matching_dr9sv.py 9sv cfhtls --field south
python legacy_surveys_matching_dr9sv.py 9sv cosmos-acs --field south
python legacy_surveys_matching_dr9sv.py 9sv hsc-dr2 --field south
python legacy_surveys_matching_dr9sv.py 9sv shela --field south
python legacy_surveys_matching_dr9sv.py 9sv spies-dr1 --field south
