python legacy_surveys_matching.py 10.1 2dfgrs --field south
python legacy_surveys_matching.py 10.1 2dflens --field south
python legacy_surveys_matching.py 10.1 2mrs --field south
python legacy_surveys_matching.py 10.1 3d-hst-v4.1.5 --field south
python legacy_surveys_matching.py 10.1 6dfgs --field south
python legacy_surveys_matching.py 10.1 ages --field south
python legacy_surveys_matching.py 10.1 c3r2-dr2 --field south
python legacy_surveys_matching.py 10.1 cfhtls --field south
python legacy_surveys_matching.py 10.1 cosmos-acs --field south
python legacy_surveys_matching.py 10.1 cosmos2015-v1.1 --field south
python legacy_surveys_matching.py 10.1 deep2 --field south
python legacy_surveys_matching.py 10.1 deep3 --field south
python legacy_surveys_matching.py 10.1 fmos-cosmos-v1.0 --field south
python legacy_surveys_matching.py 10.1 gama-dr3 --field south
python legacy_surveys_matching.py 10.1 mosdef-final --field south
python legacy_surveys_matching.py 10.1 ozdes-dr2 --field south
python legacy_surveys_matching.py 10.1 primus --field south
python legacy_surveys_matching.py 10.1 s82mgc --field south
python legacy_surveys_matching.py 10.1 sdss-dr16 --field south
python legacy_surveys_matching.py 10.1 sdss-dr16q --field south
python legacy_surveys_matching.py 10.1 shela --field south
python legacy_surveys_matching.py 10.1 spies-dr1 --field south
python legacy_surveys_matching.py 10.1 vipers-pdr2 --field south
python legacy_surveys_matching.py 10.1 vvds --field south
python legacy_surveys_matching.py 10.1 wigglez-final --field south
# python legacy_surveys_matching.py 10.1 hsc-dr3 --field south
python legacy_surveys_matching.py 10.1 desi-edr --field south
python legacy_surveys_matching.py 10.1 zcosmos_bright_dr3 --field south
python legacy_surveys_matching.py 10.1 eboss-dr16 --field south
python legacy_surveys_matching_add_pz.py 10.1 desi_lrg_xcorr --field south
